force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <description>stores the custom data related to the assignment</description>
    <label>Assignment</label>
    <nameField>
        <displayFormat>Assignment-{0000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>stores the in detail description of assignment</description>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <description>stores the due date of the assignment</description>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>stores the status of the assignment</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>stores the title of the assignment</description>
    <label>Title</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AssignmentController.cls
public class AssignmentController 
{
	@AuraEnabled(cacheable=true)
    public static List<Assignment__c> getAssignmentList() {
        return [SELECT Id, Name, Description__c, DueDate__c,Status__c, Title__c FROM Assignment__c ORDER BY DueDate__c];
    }

    @AuraEnabled
    public static Assignment__c createAssignmentRecord(Assignment__c assignmentRecord) {
        upsert assignmentRecord;
        return assignmentRecord;
    }
}